---
title: "Ween"
author: "Goutham"
date: "11/3/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
theme_set(theme_light())

horror_movies_raw <- horror_movies <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-22/horror_movies.csv")

```

```{r}
horror_movies_raw %>% 
  arrange(desc(review_rating)) %>% 
  extract(title, "year", "\\((\\d\\d\\d\\d)\\)$", remove = FALSE, convert = TRUE) %>% 
  filter(year >= 2005) %>% 
  ggplot(aes(year)) +
  geom_histogram()

```

Most of the movies are since 2012.

```{r}
horror_movies <- horror_movies_raw %>% 
  arrange(desc(review_rating)) %>% 
  extract(title, "year", "\\((\\d\\d\\d\\d)\\)$", remove = FALSE, convert = TRUE) %>% 
  mutate(budget = parse_number(budget)) %>% 
    separate(plot, c("director", "cast_sentence", "plot"), extra = "merge", sep = "\\. ", fill = "right") %>% 
  distinct(title, .keep_all = TRUE)

horror_movies %>% 
  count(genres, sort = TRUE)

horror_movies %>% 
  count(language, sort = TRUE)

# horror_movies %>% 
  # count(budget, sort = TRUE)

horror_movies %>% 
  ggplot(aes(budget)) + 
  geom_histogram() +
  scale_x_log10(label = scales::dollar)
```


Do movies with higher budget end up rated higher?
```{r}
horror_movies %>% 
  ggplot(aes(budget, review_rating)) +
  geom_point() + 
  scale_x_log10(label = scales::dollar) +
  geom_smooth(method = "lm") # Best fit regression
```
No relationship between budget and ratings.

How about movie rating and review?
```{r}
horror_movies %>% 
  mutate(movie_rating = fct_lump(movie_rating, 5),
         movie_rating = fct_reorder(movie_rating, review_rating, na.rm = TRUE)) %>% 
  # count(movie_rating, sort = TRUE) %>% 
  ggplot(aes(movie_rating, review_rating)) +
  geom_boxplot() + 
  coord_flip()

#ANOVA - Is the variance by chance?
horror_movies %>% 
  filter(!is.na(movie_rating)) %>% 
  mutate(movie_rating = fct_lump(movie_rating, 5)) %>% 
  lm(review_rating ~ movie_rating, data = .) %>% 
  anova()

# Significant F value => There is more variation in review_rating explained by movie_rating than we'd expect by chance => The variation is not by chance.
```

```{r}
horror_movies %>% 
  separate_rows(genres, sep = "\\| ") %>% 
  # select(title, year, genres) %>% 
  mutate(genre = fct_lump(genres, 5)) %>% 
  # count(genres, sort = TRUE)
  ggplot(aes(genre, review_rating)) +
  geom_boxplot()
  
```

```{r}
library(tidytext)

horror_movies_unnested <- horror_movies %>% 
  unnest_tokens(word, plot) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(!is.na(word))

horror_movies_unnested  %>% 
  filter(!is.na(review_rating)) %>% 
  # count(word, sort = TRUE)
  group_by(word) %>% 
  summarize(movies = n(),
            avg_rating = mean(review_rating)) %>% 
  arrange(desc(movies)) %>% 
  filter(movies >= 100) %>% 
  mutate(word = fct_reorder(word, avg_rating)) %>% 
  ggplot(aes(avg_rating, word)) +
  geom_point()
```

## Lasso regression for predicting review rating based on words in plot

```{r}
horror_movies %>% 
  count(title, sort = TRUE)

library(glmnet) # Lasso regression
library(Matrix)

movie_word_matrix <- horror_movies_unnested %>% 
  filter(!is.na(review_rating)) %>% 
  add_count(word) %>% 
  filter(n >= 20) %>% 
  count(title, word) %>% 
  cast_sparse(title, word, n)


rating <- horror_movies$review_rating[match(rownames(movie_word_matrix), horror_movies$title)]
# qplot(rating)
lasso_model <- cv.glmnet(movie_word_matrix, rating, )
```


```{r}
library(broom)

tidy(lasso_model$glmnet.fit) %>% 
  filter(term %in% c("friends", "evil", "college", "haunted", "mother")) %>% 
  ggplot(aes(lambda, estimate, color = term)) +
  geom_line()+
  scale_x_log10() +
  geom_hline(yintercept = 0, lty = 2)
```

```{r}
plot(lasso_model)

tidy(lasso_model$glmnet.fit) %>% 
  filter(lambda == lasso_model$lambda.min,
         term != "(Intercept)") %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(term, estimate)) +
  geom_col() +
  coord_flip()
```


Throwing everything into a linear model: director, cast, genre, rating, plot, words.

```{r}
features <- horror_movies %>% 
  filter(!is.na(review_rating)) %>% 
  select(title, genres, director, cast, movie_rating, language, release_country) %>% 
  mutate(director = str_remove(director, "Directed by")) %>% 
  gather(type, value, -title) %>% 
  filter(!is.na(value)) %>% 
  separate_rows(value, sep = "\\| ?") %>% 
  unite(feature, type, value, sep = ": ") %>% 
  mutate(n = 1)

movie_feature_matrix <- horror_movies_unnested %>% 
  filter(!is.na(review_rating)) %>% 
  count(title, feature = paste0("word: ", word)) %>% 
  bind_rows(features) %>% 
  add_count(feature) %>% 
  filter(n >= 10) %>% 
  cast_sparse(title, feature)

dim(movie_feature_matrix)

rating <- horror_movies$review_rating[match(rownames(movie_feature_matrix), horror_movies$title)]

feature_lasso_model <- cv.glmnet(movie_feature_matrix, rating)
```

```{r}
plot(feature_lasso_model)

tidy(feature_lasso_model$glmnet.fit) %>% 
  filter(lambda == feature_lasso_model$lambda.1se,
         term != "(Intercept)") %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(term, estimate)) +
  geom_col() +
  coord_flip() +
  labs(x = "",
       y = "Coeffiecient for predicting movie rating",
       title = "What affect a horror movie rating?",
       subtitle = "Based on a Lasso regression to predict IMDB ratings of ~3000 movies")
```

Which movie am i gona watch?

```{r}
horror_movies %>% 
  filter(str_detect(genres, "Comedy"),
                    !is.na(movie_rating),
                    !is.na(budget),
                    movie_rating != "PG") %>% 
  arrange(desc(review_rating)) %>% 
  select(title, review_rating, movie_rating, plot, director, budget, language) %>%
  View()
```





